How to search by date
SELECT 
  COUNT(1) AS QUANTIDADE_OPERACOES, 
  NVL(SUM(OCI.OCI_VL_OPERACAO),0) AS SOMA_OPERACOES 
FROM SA.OPERACAO_CONTA_INVESTIMENTO OCI 
JOIN PIX.ENVIO PIX_ENV 
  ON PIX_ENV.CD_OPERACAO_CONTA_INVEST = OCI.OCI_CD_OPERACAO_CONTA_INVEST 
WHERE PIX_ENV.CD_STATUS = 'ENVIADO' 
  AND OCI.OCI_DT_CADASTRO_OPERACAO 
  	BETWEEN TO_DATE('2022-11-21', 'yyyy-mm-dd') AND  TO_DATE('2022-11-21', 'yyyy-mm-dd') 
  AND OCI.OCI_CD_CONTA_CARTAO = '51880280';
  
